version: '2'

services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./:/usr/share/nginx/html/
    environment:
      VIRTUAL_HOST: twenty-one.ryanp.me

networks:
  default:
    external:
      name: proxy
